### ISSUE TITLE
Docs: All examples use double quotes, break query

### ISSUE THREAD

**Issue by cteodor** [endgameinc/eqllib#2]
All analytics examples use single quote, e.g.
process where subtype.create and
    process_name == "net.exe" and command_line == "* view*" and command_line != "*\\\\*"

whereas the query should use "process ... process_name == 'net.exe' ..." to work.
Just a cosmetic issue, but makes copy&paste easier :-)

**Comment by rw-access** [comment]
hey again @cteodor, I've been brainstorming ideas for the `eql` and `eqllib` CLIs for pasting queries better. You're right that copy and pasting isn't friendly into the CLI. One thought was actually prompting the user if it's not specified in the command line, because that would also get around the extra escaping done for command line parsing.

If you want to test a specific rule, the [survey](https://eqllib.readthedocs.io/en/latest/guides/cli.html#survey) command might be useful. Instead of cramming everything into a command line, point it to a TOML file.

thanks for the feedback--open to suggestions and hearing any other issues you find!

**Comment by rw-access** [comment]
We've since added a shell, which should help avoid any command line parsing.
I'm going to close this, but feel free to open this back up if you think it's still an issue.
